### ISSUE TITLE
Example Client create not working

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#1]
```
final client = Client(
  realm: "my.realm",transport: WebSocketTransport("wss://localhost:8443")
);
```
If I use this code from example, to create client, i  receive error: "Too many positional arguments: 0 expected, but 1 found". WebSocketTransport doesn't have arguments. Are docs outdated? If yes, can they be updated with current usage?
Also. What is correct usage for call and other methods with and without arguments? If it is possible, please update also that one.

**Comment by konsultaner** [comment]
@andzejsw  I fixed the example, checkout the [test suite for more advanced examples](https://github.com/konsultaner/connectanum-dart/blob/master/test/client_test.dart)

**Comment by andzejsw** [comment]
`Too many positional arguments: {0} expected, but {3} found.`
Still this error on WebSocketTransport.

**Comment by konsultaner** [comment]
can you try to import io or html before? The library uses conditional exports

```
import 'dart:io';
```

**Comment by andzejsw** [comment]
> import 'dart:io';

Both not working

**Comment by andzejsw** [comment]
In class Client example looks different than ir is in README. But that one also not working for me. Maybe i am using it wrong. Atleast that one is compiling for me:
    Client client = Client(
        realm: "myRealm",
        transport: SocketTransport(
            "wss://mydomain.lv/ws",
            8080,
            Serializer(),
            SocketHelper.SERIALIZATION_JSON
        )
    );

**Comment by konsultaner** [comment]
> Hostname is correct. When i type it in browser url with same port, i can acces it.

It doesn't work when I do it ;)

I pushed some new code to make the examples work as exected. Could you give it a try? I'm quite new to dart and didn't know much about conditional exports. I also added a enum class for the serializer type. so please try it as written in the example again.

**Comment by andzejsw** [comment]
> > Hostname is correct. When i type it in browser url with same port, i can acces it.
> 
> It doesn't work when I do it ;)
> 
> I pushed some new code to make the examples work as exected. Could you give it a try? I'm quite new to dart and didn't know much about conditional exports. I also added a enum class for the serializer type. so please try it as written in the example again.

I got a bit further, but still there is error: 
```
lib/src/services/WampService.dart:29:32: Error: Getter not found: 'SERIALIZATION_JSON'.
            WebSocketTransport.SERIALIZATION_JSON
```

**Comment by konsultaner** [comment]
Yes I removed it and replaced it with `WebSocketSerialization.SERIALIZATION_JSON`

**Comment by andzejsw** [comment]
> WebSocketSerialization.SERIALIZATION_JSON

Big tnx. Now it works! Please, when it is possible, update docs with change, cause someone else may run into this issue.
