### ISSUE TITLE
What is correct way of using Connectanum Error class outside package.

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#10]
I have something like this.

```
onError: (Object e) {
      print(e);
}
```
If i want to print error message, which was retrieved from server, should i implement Error class from package and use instead of Object? Or should i do it differently?

**Comment by konsultaner** [comment]
I always return the error message. I would use the packages Error instead.

**Comment by andzejsw** [comment]
It works for me only when i do object casting to package Error.
```
onError: (Object e) {
      Error err = e as Error;
      print("error: ${err.error}");
    });
```

**Comment by konsultaner** [comment]
This is a dart issue. The `onError` parameter in dart streams has no type.

https://github.com/dart-lang/sdk/blob/99b693ba889ab7fc31b8453d8c221ba154c1211e/sdk/lib/async/stream.dart#L507
