### ISSUE TITLE
Support for retention of event messages emitted from Publisher and retrieve from Subscriber end

### ISSUE THREAD

**Issue by CoDeRgAnEsh** [konsultaner/connectanum-dart#14]
It will be good if 'Event History' feature is implemented in dart.

Like when publishing an event, the publisher can set an option (retain=True) in the `PublishOptions` which will cause the Broker to retain the event being published as the most-recent event on this topic.

Same upon subscription, a client can pass (get_retained=True) in the `SubscribeOptions`. If there is any retained event, it will be immediately sent to the subscriber.

Reference: https://crossbar.io/docs/Event-History/ 

Python implementation: https://github.com/crossbario/autobahn-python/tree/master/examples/twisted/wamp/pubsub/retained

**Comment by konsultaner** [comment]
this feature is [called event retention](https://github.com/wamp-proto/wamp-proto/blob/master/rfc/text/advanced/ap_pubsub_event_retention.md) and is added in 1.0.6

**Comment by CoDeRgAnEsh** [comment]
Thanks @konsultaner for this feature implementation ✌️
