### ISSUE TITLE
Need extra exports from package

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#21]
Hi. I would like to have, that following dart files are exported from package:
```
import 'package:connectanum/src/message/goodbye.dart';
import 'package:connectanum/src/message/abstract_message.dart';
import 'package:connectanum/src/serializer/abstract_serializer.dart';
```
Currently "Dart analysis" shows for me warning, when I import these files. So it would be nice if `connectanum.dart` file also exported these files.

**Comment by konsultaner** [comment]
did it

**Comment by andzejsw** [comment]
> did it

Thanks. You really are the best!
