### ISSUE TITLE
Null safety support

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#22]
Package currently isn't supporting flutter 2.0 null safety logic.

**Comment by konsultaner** [comment]
I thought about it and found out that at the moment not all deps have nullsafty yet. I will start working at this as soon as all deps are nullsafe.

**Comment by andzejsw** [comment]
**Dependencies:** 
pointycastle: Prerelease: 3.0.0-nullsafety.2
logging: 1.0.0 null safe
pedantic: 1.11.0 null safe
meta: 1.3.0 null safe
msgpack_dart: 1.0.0 null safe
saslprep is your package @konsultaner as far as i understand. So looks like that all main dependencies are nulls safe.

Also both dev dependencies are null safe.

**Comment by konsultaner** [comment]
Seems like I have to start earlier then I thought. The problem I saw was bouncy castle. It kind of stopped development. Seems like they have continued there work. Thanks for checking my deps ✌️

**Comment by andzejsw** [comment]
@konsultaner I have created new PR (https://github.com/konsultaner/connectanum-dart/pull/31) regarding this issue. Hope it will help to speed up development. :)

**Comment by konsultaner** [comment]
Oh cool Thanks! What happened to the code coverage? Did you remove Tests?

**Comment by andzejsw** [comment]
> Oh cool Thanks! What happened to the code coverage? Did you remove Tests?

To be honest i don't know what is reason. I rewrited code, yo use null safety logic. That involved a lot of null checks. Possibly some of that was reason, why coverage rating decreased.

**Comment by konsultaner** [comment]
@andzejsw @oberstet Could someone confirm https://github.com/konsultaner/connectanum-dart/tree/sound-null-safety does work in production? I would like to finally support sound null safety.

**Comment by oberstet** [comment]
@konsultaner I'm not currently doing Dart stuff .. test quickly. OP might .. actually I don't know

**Comment by konsultaner** [comment]
@oberstet ok, thank you! I'll merge it. Upcoming issues will be posted anyways. . So What 🤔

**Comment by oberstet** [comment]
@konsultaner cool, thanks for moving things forward!

> btw, as we are talking here, and rgd the way forward with WAMP/Crossbar.io etc, you might be interested in https://github.com/wamp-proto/wamp-proto/issues/387
