### ISSUE TITLE
Binary support in JSON

### ISSUE THREAD

**Issue by oberstet** [konsultaner/connectanum-dart#25]
WAMP defines an extension to standard JSON that allows transparent support for binary value:

https://wamp-proto.org/_static/gen/wamp_latest_ietf.html#rfc.section.15

AutobahnPython and AutobahnJS support that - would be great to have it in connectanum-dart as well. It's pretty useful, and (in practice) doesn't cause issues (in most host languages)

**Comment by konsultaner** [comment]
Do you mean that in conjuntion with https://github.com/wamp-proto/wamp-proto/issues/228 ? Or in general?

**Comment by konsultaner** [comment]
I'll implement it in general, just saw that I forgot about transparent payload as well 🤯

**Comment by oberstet** [comment]
No, in general. Payload transparency is a mode where the whole args/kwargs is not a structured object, but itself just a binary value opaque to the router. Hence the name "payload transparency".

JSON binary supports allow you to eg do a call with

```
args = ["foo", 23, b'\xc0\xfc\xde\x84']
```

or 

```
kwargs = {"foo": 23, "bar": b'\xc0\xfc\xde\x84'}
```

Hence the JSON serializer/deserializer must be able to traverse/process binary values deep inside structured app payload.

In AutobahnPython, this is implemented by overriding the "string item processing" hook on the standard JSON serializer/deserializer:

https://github.com/crossbario/autobahn-python/blob/eda067aeb5cf06f88f548a10ba05383c431247f8/autobahn/wamp/serializer.py#L382

In general, this requires that the JSON serializer/deserializer _has_ hooks to do such things ... or it requires a full custom one

**Comment by konsultaner** [comment]
Yes I Did it that way 😊

**Comment by konsultaner** [comment]
I already pushed and released it

**Comment by oberstet** [comment]
^ ok, I tested it: seems to work!
