### ISSUE TITLE
v1.1.5 doesn't work ..

### ISSUE THREAD

**Issue by oberstet** [konsultaner/connectanum-dart#28]
with our test endpoint: it immediately reconnects (server side succeeds, client reconnects)

![Bildschirmfoto von 2021-03-23 18-23-29](https://user-images.githubusercontent.com/233340/112190027-e6827800-8c04-11eb-96ac-6fe6f66b0d6d.png)

my branch does work:

* https://github.com/oberstet/connectanum-dart
* https://github.com/oberstet/scratchbox/blob/master/flutter/ex1/test_client_wampcs.dart
* https://github.com/oberstet/scratchbox/blob/master/flutter/ex1/pubspec.yaml

![Bildschirmfoto von 2021-03-23 18-25-01](https://user-images.githubusercontent.com/233340/112190258-1df12480-8c05-11eb-9d42-3d27c66a5dbd.png)

**Comment by oberstet** [comment]
sorry, I don't have time to track this down - we'll continue using my branch for now, but obviously, would be great to have a working release on https://pub.dev/packages/connectanum/

**Comment by konsultaner** [comment]
Is it possible for me to connect to your testendpoint? Would make it easier to find the issue. You can also email credentials if needed.

**Comment by oberstet** [comment]
sorry, had a call. anyways, easiest would be to just "onboard" yourself. here is how:

install autobahn:

```
pip install autobahn[all]
```

> on linux, you also could use https://download.crossbario.com/xbrnetwork/linux-amd64/xbrnetwork-latest (which is a single-file executable with everything, incl. python)

check:

```
xbrnetwork version
```

start onboard:

```
xbrnetwork register-member \
	--url ws://thingcloud-box-aws.sthngs.crossbario.com:8090/ws \
	--username=oberstet2 \
	--email=tobias.ober.stein@gmail.com
```

> hit enter (select default) for everything asked

you should get an email. with codes - complete onboard:

```
xbrnetwork register-member-verify \
	--vaction=02bd637f-cc7a-4ed4-bab5-5dfd3f9ca091 \
	--vcode=4JEJ-EHH3-6ETW
```

> IMPORTANT: the email sends you the complete command to be run, but you have to remove `--url <URL>` (not needed)

then:

```
xbrnetwork get-member
```

you now can test against the URL, and using the key stored in `~/.xbrnetwork/config.ini`

I just retried, here is a complete log: https://gist.github.com/oberstet/db0cc73974ba21f20127fc59073769a2

**Comment by konsultaner** [comment]
This runs:
```
pip install autobahn[all]
```

This doesn't:
```
xbrnetwork version
```

I'm on a windows 10 machine. `wamp.exe` has been compiled, just the `xbrnetwork` has no executable.

**Comment by konsultaner** [comment]
`make install` crashes:

<details> 

```
Installing collected packages: autobahn
  Running setup.py develop for autobahn
    WARNING: Subprocess output does not appear to be encoded as cp1252
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\burkh\appdata\local\programs\python\python38-32\python.
xe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\burkh\\
ycharmProjects\\autobahn-python\\setup.py'"'"'; __file__='"'"'C:\\Users\\burkh\
PycharmProjects\\autobahn-python\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"
"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close
);exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: C:\Users\burkh\PycharmProjects\autobahn-python\
    Complete output (23 lines):
    running develop
    running egg_info
    writing autobahn.egg-info\PKG-INFO
    writing dependency_links to autobahn.egg-info\dependency_links.txt
    writing entry points to autobahn.egg-info\entry_points.txt
    writing requirements to autobahn.egg-info\requires.txt
    writing top-level names to autobahn.egg-info\top_level.txt
    package init file 'autobahn\test\__init__.py' not found (or not a regular f
le)
    package init file 'autobahn\wamp\test\__init__.py' not found (or not a regu
ar file)
    package init file 'autobahn\websocket\test\__init__.py' not found (or not a
regular file)
    package init file 'autobahn\rawsocket\test\__init__.py' not found (or not a
regular file)
    package init file 'autobahn\nvx\test\__init__.py' not found (or not a regul
r file)
    package init file 'twisted\plugins\__init__.py' not found (or not a regular
file)
    reading manifest file 'autobahn.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'autobahn.egg-info\SOURCES.txt'
    running build_ext
    generating cffi module 'build\\temp.win32-3.8\\Release\\_nvx_utf8validator.
'
    already up-to-date
    building '_nvx_utf8validator' extension
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSV
\14.24.28314\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\us
rs\burkh\appdata\local\programs\python\python38-32\include -Ic:\users\burkh\app
ata\local\programs\python\python38-32\include "-IC:\Program Files (x86)\Microso
t Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.24.28314\include" "-IC:\Progra
 Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt" "-IC:\Program Files (x8
)\Windows Kits\10\include\10.0.18362.0\shared" "-IC:\Program Files (x86)\Window
 Kits\10\include\10.0.18362.0\um" "-IC:\Program Files (x86)\Windows Kits\10\inc
ude\10.0.18362.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.
8362.0\cppwinrt" -IC:\OpenSSL-win32\include /Tcbuild\temp.win32-3.8\Release\_nv
_utf8validator.c /Fobuild\temp.win32-3.8\Release\build\temp.win32-3.8\Release\_
vx_utf8validator.obj -std=c99 -Wall -Wno-strict-prototypes -O3 -march=native    
    cl : Befehlszeile error D8021 : Ung\x81ltiges numerisches Argument /Wno-str
ct-prototypes.
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Bui
dTools\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX86\\x86\\cl.exe' failed with ex
t status 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\burkh\appdata\local\pr
grams\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.
rgv[0] = '"'"'C:\\Users\\burkh\\PycharmProjects\\autobahn-python\\setup.py'"'"'
 __file__='"'"'C:\\Users\\burkh\\PycharmProjects\\autobahn-python\\setup.py'"'"
;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"
\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"')
' develop --no-deps Check the logs for full command output.
make: *** [C:/Users/burkh/PycharmProjects/autobahn-python/Makefile:25: install] Error 1
```

</details>

**Comment by oberstet** [comment]
for windows, this reduced set should work:

```
pip install autobahn[twisted,serialization,xbr]
```

I can't test, as I don't have windows anymore. I've tested above on Linux (and it works): https://gist.github.com/oberstet/e0e5d993ef42f0dafa101463127172d8

rgd the single-file EXE for windows: in principle, that is possible, and I guess I could make it work. but I would expect this to cost at least half a day .. hard to justify for me now. why are you using a broken OS? ;)

**Comment by konsultaner** [comment]
> why are you using a broken OS? ;)

I know... don't ask me. I just never switched. 🙈

**Comment by konsultaner** [comment]
> rgd the single-file EXE for windows: in principle, that is possible, and I guess I could make it work.

dont worry I'll get it to run somehow.

**Comment by konsultaner** [comment]
> INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.

This takes for ever. Any idea on how to speed this up. I had it run for 8h and it would not finish.

**Comment by oberstet** [comment]
yes, use pip<20

https://github.com/crossbario/crossbar/blob/b4172870d077a147d5854d3aa8f5a8168e319c22/requirements-dev.txt#L17

the reason is: pip >= 20 hjas introduced a braindead new dependency resolver that doesn't really work (for dependency graphs with multiple confluent paths to the same dependent)

**Comment by konsultaner** [comment]
> yes, use pip<20

this worked!

I can't call the `xbrnetwork version` command. `xbrnetwork` is unknown executable. Do I have to call it through python? I've never used python in production. I'm a dead beginner here..

**Comment by oberstet** [comment]
try: `python -m autobahn.xbr._cli version`

```
(cpy392_1) oberstet@intel-nuci7:~$ which xbrnetwork
/home/oberstet/cpy392_1/bin/xbrnetwork
(cpy392_1) oberstet@intel-nuci7:~$ xbrnetwork version

 XBR CLI v21.3.2.dev3


   Contract addresses:

      XBRToken   : 0x87D89D00B0051E760b23a1eb7F87D38082773b55 [source: envvar $XBR_DEBUG_TOKEN_ADDR]
      XBRNetwork : 0x3970CB7F43A5A6a1ABc4f1B80D33093396b1dB4a [source: envvar $XBR_DEBUG_NETWORK_ADDR]
      XBRDomain  : 0x048137A22c3a2Df514657C9B7a32A6BEefb10ad4 [source: envvar $XBR_DEBUG_DOMAIN_ADDR]
      XBRCatalog : 0xb996F03C79574aA7a88abe8F4080b1F3F9dB8E17 [source: envvar $XBR_DEBUG_CATALOG_ADDR]
      XBRMarket  : 0xF7acf1C4CB4a9550B8969576573C2688B48988C2 [source: envvar $XBR_DEBUG_MARKET_ADDR]
      XBRChannel : 0x54037382294a7AEe37F799776C2308D087946c13 [source: envvar $XBR_DEBUG_CHANNEL_ADDR]

(cpy392_1) oberstet@intel-nuci7:~$ python -m autobahn.xbr._cli version

 XBR CLI v21.3.2.dev3


   Contract addresses:

      XBRToken   : 0x87D89D00B0051E760b23a1eb7F87D38082773b55 [source: envvar $XBR_DEBUG_TOKEN_ADDR]
      XBRNetwork : 0x3970CB7F43A5A6a1ABc4f1B80D33093396b1dB4a [source: envvar $XBR_DEBUG_NETWORK_ADDR]
      XBRDomain  : 0x048137A22c3a2Df514657C9B7a32A6BEefb10ad4 [source: envvar $XBR_DEBUG_DOMAIN_ADDR]
      XBRCatalog : 0xb996F03C79574aA7a88abe8F4080b1F3F9dB8E17 [source: envvar $XBR_DEBUG_CATALOG_ADDR]
      XBRMarket  : 0xF7acf1C4CB4a9550B8969576573C2688B48988C2 [source: envvar $XBR_DEBUG_MARKET_ADDR]
      XBRChannel : 0x54037382294a7AEe37F799776C2308D087946c13 [source: envvar $XBR_DEBUG_CHANNEL_ADDR]

(cpy392_1) oberstet@intel-nuci7:~$ 
```

**Comment by konsultaner** [comment]
Where do I get:

- XBR data market URL
- WAMP realm of the XBR data market
- private Etherum key (do i need a eutherium wallet here?)

**Comment by oberstet** [comment]
^ for the purposes of testing WAMP-cryptosign, you can just connect not to any "data market" (but see below), instead to global realm `xbrnetwork` - in which case market URL isn't needed and any Eth key (such as one random generate when running xbrnetwork CLI) can be used

once you have onboarded via above command, additionally, a member realm `member-<member_uuid>` is created and dynamiclly started. the port number of this data plane is 8080, other than the 8090 where the `xbrnetwork` realm is running

you can just use the URL with 8080, provide no realm at all, and let the router autodetect and join your client session to your personal realm

**Comment by konsultaner** [comment]
What can I do with that?
`no such profile: "default"`

**Comment by oberstet** [comment]
could you fix the library or should we continue to use my fork?

**Comment by konsultaner** [comment]
I'm trying to get xbrnetwork to run. But I'm stuck with this:

> What can I do with that?
> `no such profile: "default"`

**Comment by konsultaner** [comment]
This is actually not a bug. You used connectanum-dart in a test (what I recommended). The problem here is that if the testcase has has been executed, the test suite of dart interrupts all connections. This way we get a "connection loss". the client reconnects with the initial attempt count. Since the first retry works the reconnect count is reset again to the inital count -> infinte reconnect. Since this is no real live scenario, its not a bug.

**Comment by oberstet** [comment]
ich habe https://github.com/oberstet/scratchbox/blob/master/flutter/ex1/test_client_wampcs.dart verwendet, und das geht mit meinem branch, aber nicht mit master ...

**Comment by konsultaner** [comment]
I found the issue. It was the already discussed `authextra`. You send it as `<String,dynamic>` but I need it as `<String,String>`. What do you think? I kind of want to go to `<String,dynamic>`. Apart from that I have a really bad logging issue here. There is basically no logging at all. I should add a lot of logging to trace issues like that quicker...

![image](https://user-images.githubusercontent.com/2699538/112528523-89bdc380-8da4-11eb-9d4d-64dc0fed61f8.png)

**Comment by oberstet** [comment]
the top-level keys in authextra MUST be strings. everything else, that is top-level values or keys (!) of nested dicts, MAY be anything. I don't care what type the library uses internally to make Dart accept that. if it doesn't accept it, it is non-compliant / broken for our use though ...

**Comment by konsultaner** [comment]
I changed it. The current master will work with your code.

**Comment by oberstet** [comment]
let me test the master branch from this repo ..

**Comment by oberstet** [comment]
yes, can confirm: works with master! fantastic=)

![Bildschirmfoto von 2021-03-25 23-28-25](https://user-images.githubusercontent.com/233340/112551834-f6938680-8dc1-11eb-87d5-1020c16a3197.png)
