### ISSUE TITLE
WAMPCRA: Only derive key when `salt` present in Challenge

### ISSUE THREAD

**Issue by om26er** [konsultaner/connectanum-dart#35]
When using WAMPCRA, if the server does not send a `salt` in the challenge the Client should not try to derive the key, this is broken. It seems `connectanum-dart` does not check if `salt` is present in server's response and always tries to derive the key. This of course means the authentication fails

Here is the relevant code https://github.com/konsultaner/connectanum-dart/blob/910038b106c571abfbe789fd17b7d72eefcbc337/lib/src/authentication/cra_authentication.dart#L50

**Comment by oberstet** [comment]
sounds great! fwiw, here are some test vectors we use for PBKDF2 - that is what is used with salted WAMP-CRA

https://github.com/crossbario/autobahn-python/blob/a35f22eeaafca7568f1deb35c4a1b82ae78f77d4/autobahn

we should add WAMP-CRA level tests (salted and unsalted) using the vectors Richard added here ..

**Comment by konsultaner** [comment]
> we should add WAMP-CRA level tests (salted and unsalted) using the vectors

That would be great!
