### ISSUE TITLE
Session call arguments type

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#38]
I think session.call arguments should allow `List<dynamic>?` to be set as type, instead of just `List<Object>?`, as it is currently.

PS: Very happy to see, that there is null safe version right now. Big thanks for that.

**Comment by konsultaner** [comment]
@andzejsw yes I tried to replace all `List<Object>` with `List<dynamic>`... Can you link the line if code you are talking about?

> Very happy to see, that there is null safe version right now. Big thanks for that.

I finally got to do it. I wish I had more time.

**Comment by andzejsw** [comment]
> @andzejsw yes I tried to replace all `List<Object>` with `List<dynamic>`... Can you link the line if code you are talking about?
> 
> > Very happy to see, that there is null safe version right now. Big thanks for that.
> 
> I finally got to do it. I wish I had more time.

This line: https://github.com/konsultaner/connectanum-dart/blob/8b22e6f140f5e2921f1b99265fc191aa60b4f8ff/lib/src/protocol/session.dart#L226
