### ISSUE TITLE
Is there planed builder?

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#4]
Currently when i want to create client, with and without `authid`, i need to wrap whole creation logic inside if condition. With builder i would be able to create client without duplicate code. Currently i am doing it like this: 
```
    if(authId.isEmpty) {
      client = Client(
        realm: "myRealm",
        transport: WebSocketTransport(
            "wss://myws.lv/cws",
            new Serializer(),
            WebSocketSerialization.SERIALIZATION_JSON
        ),
      );
    } else {
      client = Client(
        realm: "myRealm",
        transport: WebSocketTransport(
            "wss://myws.lv/cws",
            new Serializer(),
            WebSocketSerialization.SERIALIZATION_JSON
        ),
        authId: authId,
        authenticationMethods: [CraAuthentication(authId)],
      );
```
Expecting something like this: 
```
        if (!authId.isEmpty) {
            builder.withAuthId(authId);
        }
```
PS: I  am doing something like this in my android project, who is using `Jawampa`. `Jawampa` also has builder.

**Comment by konsultaner** [comment]
You could also do something like this:

```dart
client = Client(
    realm: "myRealm",
    transport: WebSocketTransport(
        "wss://myws.lv/cws",
        new Serializer(),
        WebSocketSerialization.SERIALIZATION_JSON
    ),
    authId: authId.isEmpty?null:authId,
    authenticationMethods: authId.isEmpty?null:[CraAuthentication(authId)]
);
```

**Comment by andzejsw** [comment]
> You could also do something like this:
> 
> ```dart
> client = Client(
>     realm: "myRealm",
>     transport: WebSocketTransport(
>         "wss://myws.lv/cws",
>         new Serializer(),
>         WebSocketSerialization.SERIALIZATION_JSON
>     ),
>     authId: authId.isEmpty?null:authId,
>     authenticationMethods: authId.isEmpty?null:[CraAuthentication(authId)]
> );
> ```

Oh. Big tnx. Didn't knew that. I am new to dart.

**Comment by konsultaner** [comment]
In dart all optional parameters are initialized with null. I guess the builder pattern is not necessary for languages that have optional parameters, because there is no API break when changing these parameters.

**Comment by andzejsw** [comment]
Yes. I agree.
