### ISSUE TITLE
Is there a way to recreate Client?

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#5]
Currently at the beginning i am logging in unauthorised. At some point i am calling reconnect method, where i create client again. Client is created without any errors. But after that, when i make session call method request, it leads to this error:

```
    Session.call (package:connectanum/src/protocol/session.dart:192:9)<asynchronous suspension>
    #1      WampService.call (package:smartmex/src/services/WampService.dart:49:25)
    #2      LoginView.continueValidation.<anonymous closure>.<anonymous closure> (package:smartmex/src/screen/Login.dart:95:23)
    #3      _rootRunUnary (dart:async/zone.dart:1134:38)
    #4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
    #5      _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
    #6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:338:11)
    #7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:265:7)
    #8      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:377:20)
    #9      _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:252:5)
    #10     _AsBroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:476:11)
    #11     _rootRunUnary (dart:async/zone.dart:1134:38)
    #12     _CustomZone.runUnary (dart:asy
```

My reconnect method looks like this:
```
  void reconnect(String authid) {
    print('wamp reconnect $authid');
    disconnect();
    connectWampClient(authid);
  }
```
In disconnect method currently i am just nulling session, till there will be method available, to also close session.

I am creating Client with Ticket auth: 
```
    Client client = Client(
      realm: "myRealm",
      transport: WebSocketTransport(
          "wss://myWs.lv/cws",
          new Serializer(),
          WebSocketSerialization.SERIALIZATION_JSON
      ),
      authId: authId,
      authenticationMethods: authId == null ? null : [TicketAuthentication(authId)],
    );
```

**Comment by andzejsw** [comment]
Error was actually somewhere else. Before `session.dart:192` line i printed out `result.error` object and it showed, that my session was unauthorised. So it looks like client create with `authid` didn't worked. But i am surprised, that error message for `call().OnError` didn't contained it.

**Comment by konsultaner** [comment]
So its more an unexpected behavior. You expect the call to not throw the error itself but the stream right? I have to check if that is possible or if the stream closes on error. If the stream closes, I would have to reinitalize the whole input stream. I don't know if that is a performance issue.

**Comment by konsultaner** [comment]
can you show me your call code?

**Comment by andzejsw** [comment]
> So its more an unexpected behavior. You expect the call to not throw the error itself but the stream right? I have to check if that is possible or if the stream closes on error. If the stream closes, I would have to reinitalize the whole input stream. I don't know if that is a performance issue.

Nope. My call method just isn't `OnError` retrieving error message, which was send by server. Instead it just shows stream error.
I am calling call method like this: 

```
    widget.wamp.call("rpc.procededure.url").listen((r) {
      print(r);
    }).onError((Exception e, StackTrace t) {
      print(t);
    });
```
and my call code is this: 
```
  Stream<dynamic> call(String procedure, {List<Object> arguments, Map<String, Object> argumentsKeywords}) {
    return this.session.call(procedure, arguments: arguments, argumentsKeywords: argumentsKeywords, options: CallOptions(disclose_me: true, timeout: 20));
  }
```

**Comment by konsultaner** [comment]
Checkout this unit test: https://github.com/konsultaner/connectanum-dart/blob/master/test/client_test.dart#L390

It should actually work

**Comment by konsultaner** [comment]
This is wrong:

>    widget.wamp.call("rpc.procededure.url").listen((r) {
>          print(r);
>        }).onError((Exception e, StackTrace t) {
>          print(t);
>        });

The `onError` only handles errors of your listen method. so if `print(r)` would raise an error you could handle it with this.

do it like this:

``` dart
widget.wamp.call("rpc.procededure.url").listen((r) {
    print(r); 
},onError: (Exception e, StackTrace t) {
    print(t);
});
```

**Comment by konsultaner** [comment]
by the way timeout is not yet supported. if the router sopports it, it will be sent, but it is not auto-canceling the call yet.
