### ISSUE TITLE
Implement Payload PassThru Mode

### ISSUE THREAD

**Issue by KSDaemon** [konsultaner/connectanum-dart#51]
Add new AP Feature: `Payload PassThru Mode` (PPT for short)

More info in SPEC: https://wamp-proto.org/wamp_latest_ietf.html#name-payload-passthru-mode

**Comment by KSDaemon** [comment]
I'm working on that

**Comment by konsultaner** [comment]
@KSDaemon I cleaned up the PR according to darts lint tool and also put the abstract payload classes into the message folder where I think they belong to.

You added a TODO in EE2E Payload. Is there any plan you will add this to connectanum-dart as well?

Is there anything left regarding ppt I would have to do?

**Comment by KSDaemon** [comment]
Hi @konsultaner Cool! Thnx! I'll have a look!

PPT mode is done. Nothing else is needed.

Regarding TODO comments — yeah, i want to add E2EE later. In first place, I want to finish E2EE in WAMP spec and then implement it. So please don't remove E2EE blocks in code.

**Comment by KSDaemon** [comment]
As #53 is merged. Closing as implemented.
