### ISSUE TITLE
Currently the connection doesn't support authextra

### ISSUE THREAD

**Issue by cydrickn** [konsultaner/connectanum-dart#57]
Currently Client does not support additional field authextra

Where the current Client only supports arguments:
- transport
- authid
- authroles
- realms
- authenticationMethods
- isolateCount

In this issue, I'm looking forward to support the authextra
authextra:  If provided, this data is passed to the router during the connection, which the router may use to further customize the challenge to the client.

This is authextra is documented here: https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md
<img width="1078" alt="Screenshot 2023-08-22 at 11 02 29 PM" src="https://github.com/konsultaner/connectanum-dart/assets/6417652/834a2ec3-0b44-4836-81f3-c97962bde5e5">

**Comment by cydrickn** [comment]
#58

**Comment by konsultaner** [comment]
#58 has been merged
