### ISSUE TITLE
Unable to catch error

### ISSUE THREAD

**Issue by cydrickn** [konsultaner/connectanum-dart#59]
Currently im was trying to catch and error such as `wamp.error.no_such_procedure` `wamp.error.no_such_subscription`
But I was unable to catch this error. Noting happen in onError of the stream.

Example code:
this example is when the session already connected

```dart

session.call('no-procedure').listen(
  (result) => print(result.arguments![0]),
  onError: (e) {
    // it does not went here even the procedure is not exists
      var error = e as Error; 
      print(error.error);
  }
);
```

**Comment by konsultaner** [comment]
Could you please debug by setting a breakpoint there:

https://github.com/konsultaner/connectanum-dart/blob/0019a2997e230785c633576687ca85f5894320fe/lib/src/protocol/session.dart#L279

Make sure an error is received. Maybe there is a serialization problem and the Error is not recognized as an error?

**Comment by cydrickn** [comment]
Already debug it, but unfortunately it does not went to the condition and even does not send an error, in other terms it does not went inside the function.

**Comment by konsultaner** [comment]
There is a unit test on this. Maybe the channel was closed by the router before? Did you check with wireshark if a message was even sent?

**Comment by konsultaner** [comment]
ok, thats great thank you!

**Comment by konsultaner** [comment]
fixed by #60

**Comment by cydrickn** [comment]
Hi @konsultaner, should we also update the version to 2.0.4?

**Comment by konsultaner** [comment]
new version should be available in pub.dev soon
