### ISSUE TITLE
Subscription Revocation

### ISSUE THREAD

**Issue by andzejsw** [konsultaner/connectanum-dart#9]
As far as i see, there is not implemented `Subscription Revocation`. Is it planed soon? 
Until then, is it just enough, if i am using just `cancel` method on `StreamSubscription`?

**Comment by konsultaner** [comment]
Hey @andzejsw I could implement it for you. It doesn't seem to be very hard ;)

**Comment by andzejsw** [comment]
Hey. It would be very great and useful!

**Comment by konsultaner** [comment]
@andzejsw could you give it a try?

https://github.com/konsultaner/connectanum-dart/blob/0be108d3fdf525fda3a2be3ef9c854234e5fd243/example/main.dart#L26

**Comment by andzejsw** [comment]
How can i manually force unsubscribe for specific uri?

**Comment by konsultaner** [comment]
the session object has a unsubscribe method. Just call it with the subscription id:

https://github.com/konsultaner/connectanum-dart/blob/72b9e1c15740bd3885a96f64f10ddb8b63f194de/lib/src/protocol/session.dart#L249

**Comment by andzejsw** [comment]
Tnx. It works. Is there also check if subscriotion is already unsubscribed!?

**Comment by konsultaner** [comment]
No, because this is router dependant. you may use the [subscription meta api](https://crossbar.io/docs/Subscription-Meta-Events-and-Procedures/) to check this.
